name: semester_os
description: "学期OS：课程导入与学期事务管理"
publish_to: 'none'
version: 0.1.0+7

environment:
  sdk: ^3.12.2

dependencies:
  audio_session: 0.2.2
  cupertino_icons: 1.0.9
  crypto: 3.0.7
  dio: ^5.11.1
  drift: 2.28.2
  fl_chart: 1.2.0
  flutter:
    sdk: flutter
  flutter_markdown_plus: 1.0.12
  flutter_local_notifications: 22.3.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  flutter_secure_storage: ^11.2.0
  go_router: ^18.0.1
  image_picker: 1.2.0
  image_picker_android: 0.8.13+5
  just_audio: 0.10.5
  path_provider: ^2.1.6
  record: 6.1.2
  record_android: 1.4.5
  sqlite3_flutter_libs: 0.5.39
  timezone: ^0.11.1
  webview_flutter: ^4.14.1
  forui: 0.25.0
  smooth_sheets: 1.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/haut_reader.js
    - assets/hlju_reader.js
